name: AutoDeploy

# Triggers deployment of code to test servers
on:
  workflow_call:
    # inputs: will be the various git ones
    inputs:
      git_repo:
        description: "The github repository to act on"
        required: false
        default: ${{github.repository}}
        type: string
      git_banch:
        description: "The branch the commit is on"
        required: false
        default: ${{github.ref_name}}
        type: string
      git_sha:
        description: "SHA of commit"
        required: false
        default: ${{github.sha}}
        type: string
      git_actor:
        description: "The user making ht commit"
        required: false
        default: ${{github.actor}}
        type: string
      git_owner:
        description: "The owner/organization of repository"
        required: false
        default: ${{github.repository_owner}}
        type: string

    secrets:
      AZURE_AUTODEPLOY_TOKEN:
        description: "Token to trigger azure pipeline"
        required: true

jobs:
  print_settings:
    runs-on: ubuntu-latest
    steps:
      - id: "Output_vars"
        run: echo "MyRepo is ${{inputs.git_repo}} sha is ${{inputs.git_sha}} actor is ${{inputs.git_actor}} branch is ${{inputs.git_banch}} ownser is ${{inputs.git_owner}} ${{secrets.server_token}}"
  #

  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        #uses: Azure/pipelines@v1.2
        uses: wwpdb/pipelines@wwPDB
        with:
          azure-devops-project-url: https://dev.azure.com/wwPDB/wwPDB%20Python%20Projects
          azure-pipeline-name: "wwPDB.azure_autodeploy_pipeline"
          azure-devops-token: ${{ secrets.AZURE_AUTODEPLOY_TOKEN }}
          azure-pipeline-variables: '{"git_repo": "${{inputs.git_repo}}", "git_branch": "${{inputs.git_banch}}", "git_sha": "${{inputs.git_sha}}", "git_actor": "${{inputs.git_actor}}", "git_owner": "${{inputs.git_owner}}"}'
